name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js ${{ matrix.node-version }}
      if: contains(github.event.commits[0].message, '[skip ci]') == false && contains(github.event.commits[0].message, '[ci skip]') == false
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      if: contains(github.event.commits[0].message, '[skip ci]') == false && contains(github.event.commits[0].message, '[ci skip]') == false
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: upload code coverage
      if: contains(github.event.commits[0].message, '[skip ci]') == false && contains(github.event.commits[0].message, '[ci skip]') == false
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}